```{r}
library(tidyverse)
library(lubridate)

options(scipen = 1000000)

age_pyramid <- read.csv("assets/age-pyramids.csv", sep = ";") %>%
  rename(year = ANNEE, sex = SEXE, age = AGE, pop = POP) %>%
  mutate(sex = as.factor(sex))

deaths2020to2021 <- rbind(
  read.csv("assets/individual-deaths/deces_2020.csv", sep = ";"),
  read.csv("assets/individual-deaths/deces_2021_M01.csv", sep = ";"),
  read.csv("assets/individual-deaths/deces_2021_M02.csv", sep = ";"),
  read.csv("assets/individual-deaths/deces_2021_M03.csv", sep = ";"),
  read.csv("assets/individual-deaths/deces_2021_M04.csv", sep = ";"),
  read.csv("assets/individual-deaths/deces_2021_M05.csv", sep = ";"),
  read.csv("assets/individual-deaths/deces_2021_M06.csv", sep = ";")
) %>%
  rename(birth_year = datenaiss, year = datedeces, sex = sexe) %>%
  mutate(birth_year = as.integer(substr(birth_year, 0, 4))) %>%
  mutate(year = as.integer(substr(year, 0, 4))) %>%
  filter(year != 0 & birth_year != 0) %>%
  filter(year >= 2020) %>%
  # Remove overseas deaths
  filter(!startsWith(lieudeces, "97") & !startsWith(lieudeces, "98")) %>%
  mutate(age = year - birth_year) %>%
  mutate(sex = as.factor(recode(sex, "1" = "M", "2" = "F"))) %>%
  count(year, age, sex, name = "deaths")

deaths1968to2019 <- read.csv("assets/deaths.csv", sep = ";") %>%
  rename(
    sex = SEXE, year = ANNEE_1962_2019,
    age = AGE_ATTEINT_R, deaths = DECES
  ) %>%
  mutate(sex = as.factor(recode(sex, "H" = "M", "F" = "F"))) %>%
  # Remove deaths for "all ages"
  filter(age != "DEC") %>%
  mutate(age = as.integer(sub(".", "", age))) %>%
  # Metropolitan France only, and remove "both sex" counts
  filter(CHAMP == "FM" & (sex == "M" | sex == "F")) %>%
  select(year, age, sex, deaths)

deaths <- union(deaths1968to2019, deaths2020to2021) %>%
  mutate(age = ifelse(age > 99, 99, age)) %>%
  group_by(year, age, sex) %>%
  summarise(deaths = sum(deaths)) %>%
  left_join(age_pyramid, by = c("year", "age", "sex"))
```

```{r, fig.width=16, fig.height=8}
deaths %>%
  filter(year == 2020 | year == 2017 | year == 2000 | year == 1980) %>%
  mutate(death_rate = deaths / pop) %>%
  ggplot(aes(age, death_rate, color = as.factor(year))) +
  facet_grid(~sex) +
  scale_y_log10() +
  geom_line(size = 1) +
  labs(
    x = "Age", y = "Death rate",
    color = "Year", title = "Death rate per age"
  )
```

```{r, fig.width=16}
deaths %>%
  filter(year >= 1962 & year < 2021) %>%
  group_by(year, sex) %>%
  summarise(deaths = sum(deaths)) %>%
  ggplot(aes(year, deaths, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Year", y = "Deaths",
    fill = "Sex", title = "Deaths per year"
  )
```

```{r, fig.width=16}
ref_year <- 2020

deaths %>%
  filter(year >= 1962 & year < 2021) %>%
  group_by(year, sex) %>%
  summarise(deaths = sum(deaths), pop = sum(pop)) %>%
  mutate(normalized_deaths = deaths / pop) %>%
  ggplot(aes(year, normalized_deaths, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Year", y = "Deaths",
    fill = "Sex", title = "Death rate per year"
  )
```

```{r, fig.width=16}
ref_year <- 2020

deaths %>%
  left_join(
    age_pyramid %>%
      filter(year == ref_year) %>%
      rename(ref_pop = pop) %>%
      select(ref_pop, age, sex),
    by = c("age", "sex")
  ) %>%
  mutate(normalized_deaths = deaths / pop * ref_pop) %>%
  filter(year >= 1962 & year < 2021) %>%
  group_by(year, sex) %>%
  summarise(normalized_deaths = sum(normalized_deaths)) %>%
  ggplot(aes(year, normalized_deaths, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Year", y = "Deaths", fill = "Sex",
    title = paste("Deaths per year normalized to ",
      ref_year, "'s age pyramid",
      sep = ""
    )
  )
```
